name: sample
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - python=3.7
  - pyarrow=1.0.0
  - keras=2.3.1
  - matplotlib
  - numpy=1.18.1
  - tensorflow=1.13.1
  - scikit-learn
  - scipy>0.15
  - obspy
